### ISSUE TITLE
Text ignored after %

### ISSUE THREAD

**Issue by senthilmm** [osbornemj/text2bib#1]
If the Journal title has percentage symbol, the text following it is ignored.

% L. M. Zhang, and F. R. Kschischang, "Staircase Codes With 6Technology 32, 1999-2002 (2014). 
@unpublished{zk,
  author = {L. M. Zhang and F. R. Kschischang},
  title = {Staircase Codes With 6Technology 32, 1999-2002 (2014)},

Actual input:
L. M. Zhang, and F. R. Kschischang, "Staircase Codes With 6% to 33% Overhead," Journal of Lightwave
Technology 32, 1999-2002 (2014).

**Comment by osbornemj** [comment]
That is correct.  The percentage symbol in TeX is a comment character.  If you want the algorithm to treat it as a regular symbol, you need to choose that option in the upload form.

**Comment by senthilmm** [comment]
Thanks. Apologize for the oversight.
